version: '2'
services:
    nginx:
        image: nginx:latest
        ports:
            - "8084:80"
            - "4434:443"
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs:/var/log/nginx
